
package TresEnRaya;

import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author sebassvr
 */
public class VentanaJuego extends javax.swing.JFrame{
    // objeto de VentanaInicio
    VentanaInicio vInicio = new VentanaInicio();
    // imagenes
    final ImageIcon amongAzul = new ImageIcon(getClass().getResource("/imagenesTresEnRaya/imagenAmongAzul.png"));
    final ImageIcon amongCafeClaro = new ImageIcon(getClass().getResource("/imagenesTresEnRaya/imagenAmongCafeClaro.png"));
    private String usuarioTurno1;
    private String usuarioTurno2;
    private int turnos = 0;
    private boolean turno1 = true;
    private boolean turno2 = false;
    private String puesto1 = "0";
    private String puesto2 = "0";
    private String puesto3 = "0";
    private String puesto4 = "0";
    private String puesto5 = "0";
    private String puesto6 = "0";
    private String puesto7 = "0";
    private String puesto8 = "0";
    private String puesto9 = "0";
    private String ganador = "0";
    private int victoriasUsuarioTurno1 = 0;
    private int victoriasUsuarioTurno2 = 0;
    private int empates = 0;
    VentanaGanador vGanador;
    private String prueba1 = vInicio.getUsuario1();
    private String prueba2 = vInicio.getUsuario2();

    public String getPrueba1() {
        return prueba1;
    }

    public void setPrueba1(String prueba1) {
        this.prueba1 = prueba1;
    }

    public String getPrueba2() {
        return prueba2;
    }

    public void setPrueba2(String prueba2) {
        this.prueba2 = prueba2;
    }
    
    
    

    
    
    /**
     * Creates new form VentanaJuego
     */
    public VentanaJuego(String usuarioTurno1,String usuarioTurno2) {
        initComponents();
        this.usuarioTurno1 = usuarioTurno1;
        this.usuarioTurno2 = usuarioTurno2;
        this.setSize(800, 600);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelJuego = new javax.swing.JPanel();
        lugar1 = new javax.swing.JButton();
        lugar2 = new javax.swing.JButton();
        lugar3 = new javax.swing.JButton();
        lugar4 = new javax.swing.JButton();
        lugar5 = new javax.swing.JButton();
        lugar6 = new javax.swing.JButton();
        lugar7 = new javax.swing.JButton();
        lugar8 = new javax.swing.JButton();
        lugar9 = new javax.swing.JButton();
        menuJuego = new javax.swing.JMenuBar();
        opcionesJuego = new javax.swing.JMenu();
        comenzardeNuevo = new javax.swing.JMenuItem();
        mostrarResultados = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        salir = new javax.swing.JMenuItem();
        opcionAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        panelJuego.setBackground(new java.awt.Color(0, 255, 0));
        panelJuego.setForeground(new java.awt.Color(255, 255, 255));
        panelJuego.setLayout(new java.awt.GridLayout(3, 3, 3, 3));

        lugar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugar1ActionPerformed(evt);
            }
        });
        panelJuego.add(lugar1);

        lugar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugar2ActionPerformed(evt);
            }
        });
        panelJuego.add(lugar2);

        lugar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugar3ActionPerformed(evt);
            }
        });
        panelJuego.add(lugar3);

        lugar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugar4ActionPerformed(evt);
            }
        });
        panelJuego.add(lugar4);

        lugar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugar5ActionPerformed(evt);
            }
        });
        panelJuego.add(lugar5);

        lugar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugar6ActionPerformed(evt);
            }
        });
        panelJuego.add(lugar6);

        lugar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugar7ActionPerformed(evt);
            }
        });
        panelJuego.add(lugar7);

        lugar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugar8ActionPerformed(evt);
            }
        });
        panelJuego.add(lugar8);

        lugar9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lugar9ActionPerformed(evt);
            }
        });
        panelJuego.add(lugar9);

        opcionesJuego.setText("Juego");

        comenzardeNuevo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comenzardeNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesTresEnRaya/comenzardeNuevoIcon.png"))); // NOI18N
        comenzardeNuevo.setText("Comenzar de Nuevo");
        opcionesJuego.add(comenzardeNuevo);

        mostrarResultados.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        mostrarResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesTresEnRaya/leaderBoardIcon.png"))); // NOI18N
        mostrarResultados.setText("Mostrar Resultados");
        opcionesJuego.add(mostrarResultados);
        opcionesJuego.add(jSeparator1);

        salir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesTresEnRaya/botonSalir.png"))); // NOI18N
        salir.setText("Salir");
        opcionesJuego.add(salir);

        menuJuego.add(opcionesJuego);

        opcionAyuda.setText("Ayuda");
        menuJuego.add(opcionAyuda);

        setJMenuBar(menuJuego);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelJuego, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lugar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugar1ActionPerformed
        if(turno1 == true && puesto1.equals("0")){
            lugar1.setIcon(amongAzul);
            turno1 = false;
            turno2 = true;
            puesto1 = "1";
            turnos++;
        }
        else if(puesto1.equals("0")) {
            lugar1.setIcon(amongCafeClaro);
            turno2 = false;
            turno1 = true;
            puesto1 = "2";
            turnos++;
        }
        verificar();
    }//GEN-LAST:event_lugar1ActionPerformed

    private void lugar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugar2ActionPerformed
        if(turno1 == true && puesto2.equals("0")){
            lugar2.setIcon(amongAzul);
            turno1 = false;
            turno2 = true;
            puesto2 = "1";
            turnos++;
        }
        else if(puesto2.equals("0")) {
            lugar2.setIcon(amongCafeClaro);
            turno2 = false;
            turno1 = true;
            puesto2 = "2";
            turnos++;
        }
        verificar();
    }//GEN-LAST:event_lugar2ActionPerformed

    private void lugar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugar3ActionPerformed
        if(turno1 == true && puesto3.equals("0")){
            lugar3.setIcon(amongAzul);
            turno1 = false;
            turno2 = true;
            puesto3 = "1";
            turnos++;
        }
        else if(puesto3.equals("0")) {
            lugar3.setIcon(amongCafeClaro);
            turno2 = false;
            turno1 = true;
            puesto3 = "2";
            turnos++;
        }
        verificar();
    }//GEN-LAST:event_lugar3ActionPerformed

    private void lugar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugar4ActionPerformed
        if(turno1 == true && puesto4.equals("0")){
            lugar4.setIcon(amongAzul);
            turno1 = false;
            turno2 = true;
            puesto4 = "1";
            turnos++;
        }
        else if(puesto4.equals("0")) {
            lugar4.setIcon(amongCafeClaro);
            turno2 = false;
            turno1 = true;
            puesto4 = "2";
            turnos++;
        }
        verificar();
    }//GEN-LAST:event_lugar4ActionPerformed

    private void lugar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugar5ActionPerformed
        if(turno1 == true && puesto5.equals("0")){
            lugar5.setIcon(amongAzul);
            turno1 = false;
            turno2 = true;
            puesto5 = "1";
            turnos++;
        }
        else if(puesto5.equals("0")) {
            lugar5.setIcon(amongCafeClaro);
            turno2 = false;
            turno1 = true;
            puesto5 = "2";
            turnos++;
        }
        verificar();
    }//GEN-LAST:event_lugar5ActionPerformed

    private void lugar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugar6ActionPerformed
        if(turno1 == true && puesto6.equals("0")){
            lugar6.setIcon(amongAzul);
            turno1 = false;
            turno2 = true;
            puesto6 = "1";
            turnos++;
        }
        else if(puesto6.equals("0")) {
            lugar6.setIcon(amongCafeClaro);
            turno2 = false;
            turno1 = true;
            puesto6 = "2";
            turnos++;
        }
        verificar();
    }//GEN-LAST:event_lugar6ActionPerformed

    private void lugar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugar7ActionPerformed
        if(turno1 == true && puesto7.equals("0")){
            lugar7.setIcon(amongAzul);
            turno1 = false;
            turno2 = true;
            puesto7 = "1";
            turnos++;
        }
        else if(puesto7.equals("0")) {
            lugar7.setIcon(amongCafeClaro);
            turno2 = false;
            turno1 = true;
            puesto7 = "2";
            turnos++;
        }
        verificar();
    }//GEN-LAST:event_lugar7ActionPerformed

    private void lugar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugar8ActionPerformed
        if(turno1 == true && puesto8.equals("0")){
            lugar8.setIcon(amongAzul);
            turno1 = false;
            turno2 = true;
            puesto8 = "1";
            turnos++;
        }
        else if(puesto8.equals("0")) {
            lugar8.setIcon(amongCafeClaro);
            turno2 = false;
            turno1 = true;
            puesto8 = "2";
            turnos++;
        }
        verificar();
    }//GEN-LAST:event_lugar8ActionPerformed

    private void lugar9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lugar9ActionPerformed
        if(turno1 == true && puesto9.equals("0")){
            lugar9.setIcon(amongAzul);
            turno1 = false;
            turno2 = true;
            puesto9 = "1";
            turnos++;
        }
        else if(puesto9.equals("0")) {
            lugar9.setIcon(amongCafeClaro);
            turno2 = false;
            turno1 = true;
            puesto9 = "2";
            turnos++;
        }
        verificar();
    }//GEN-LAST:event_lugar9ActionPerformed

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         /* Set the look and feel */
       try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.fast.FastLookAndFeel");
        } catch (ClassNotFoundException ex) {
            //Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            //Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            //Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            //Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        String usuarioTurno1 = "NombreTurno1";
        String usuarioTurno2 = "NombreTurno2";
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaJuego(usuarioTurno1, usuarioTurno2).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem comenzardeNuevo;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JButton lugar1;
    private javax.swing.JButton lugar2;
    private javax.swing.JButton lugar3;
    private javax.swing.JButton lugar4;
    private javax.swing.JButton lugar5;
    private javax.swing.JButton lugar6;
    private javax.swing.JButton lugar7;
    private javax.swing.JButton lugar8;
    private javax.swing.JButton lugar9;
    private javax.swing.JMenuBar menuJuego;
    private javax.swing.JMenuItem mostrarResultados;
    private javax.swing.JMenu opcionAyuda;
    private javax.swing.JMenu opcionesJuego;
    private javax.swing.JPanel panelJuego;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables

    private void verificar(){
        obtenerGanador();
        if (ganador.equals("1") || ganador.equals("2")) {
            if (ganador.equals("1")) {
                // gano usuarioturno1
                victoriasUsuarioTurno1++;
                vGanador = new VentanaGanador(this, true, usuarioTurno1);
                vGanador.setVisible(true);
            }
            else {
                // gano usuarioturno2
                victoriasUsuarioTurno2++;
                vGanador = new VentanaGanador(this, true, usuarioTurno2);
                vGanador.setVisible(true);
            }
        }
        else if(turnos == 10){
            // Empate
            empates++;
            //mostrar ventana de empates....
        }
    }
    
    private void obtenerGanador() {
        // Cuando gane UsuarioTurno1 :
        if (puesto1.equals("1") && puesto2.equals("1") && puesto3.equals("1")) {
            ganador = "1";
        }
        else if (puesto4.equals("1") && puesto5.equals("1") && puesto6.equals("1")) {
            ganador = "1";
        }
        else if (puesto7.equals("1") && puesto8.equals("1") && puesto9.equals("1")) {
            ganador = "1";
        }
        else if (puesto1.equals("1") && puesto4.equals("1") && puesto7.equals("1")) {
            ganador = "1";
        }
        else if (puesto2.equals("1") && puesto5.equals("1") && puesto8.equals("1")) {
            ganador = "1";
        }
        else if (puesto3.equals("1") && puesto6.equals("1") && puesto9.equals("1")) {
            ganador = "1";
        }
        else if (puesto1.equals("1") && puesto5.equals("1") && puesto9.equals("1")) {
            ganador = "1";
        }
        else if (puesto7.equals("1") && puesto5.equals("1") && puesto3.equals("1")) {
            ganador = "1";
        }
        
        //Cuando gane UsuarioTurno2 :
        if (puesto1.equals("2") && puesto2.equals("2") && puesto3.equals("2")) {
            ganador = "2";
        }
        else if (puesto4.equals("2") && puesto5.equals("2") && puesto6.equals("2")) {
            ganador = "2";
        }
        else if (puesto7.equals("2") && puesto8.equals("2") && puesto9.equals("2")) {
            ganador = "2";
        }
        else if (puesto1.equals("2") && puesto4.equals("2") && puesto7.equals("2")) {
            ganador = "2";
        }
        else if (puesto2.equals("2") && puesto5.equals("2") && puesto8.equals("2")) {
            ganador = "2";
        }
        else if (puesto3.equals("2") && puesto6.equals("2") && puesto9.equals("2")) {
            ganador = "2";
        }
        else if (puesto1.equals("2") && puesto5.equals("2") && puesto9.equals("2")) {
            ganador = "2";
        }
        else if (puesto7.equals("2") && puesto5.equals("2") && puesto3.equals("2")) {
            ganador = "2";
        }
    }
    
    
    
    
}
