
package TresEnRaya;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author sebassvr
 */
public class VentanaGanador extends javax.swing.JDialog {
    String usuarioTurnoGanador;
    
    
    /**
     * Creates new form VentanaGanador
     */
    public VentanaGanador(java.awt.Frame parent, boolean modal, String usuarioTurnoGanador) {
        super(parent, modal);
        this.usuarioTurnoGanador = usuarioTurnoGanador;
        initComponents();
        etiquetaMostrarGanador.setText("Winner "+usuarioTurnoGanador);
        this.setLocationRelativeTo(null);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVentanaGanador = new javax.swing.JPanel();
        etiquetaMostrarGanador = new javax.swing.JLabel();
        etiquetaFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 500, 500));
        setResizable(false);

        panelVentanaGanador.setMaximumSize(new java.awt.Dimension(500, 500));
        panelVentanaGanador.setMinimumSize(new java.awt.Dimension(500, 500));
        panelVentanaGanador.setPreferredSize(new java.awt.Dimension(500, 500));
        panelVentanaGanador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaMostrarGanador.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        etiquetaMostrarGanador.setForeground(new java.awt.Color(51, 51, 0));
        etiquetaMostrarGanador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaMostrarGanador.setText("Winner Sebastian");
        etiquetaMostrarGanador.setAlignmentY(0.0F);
        panelVentanaGanador.add(etiquetaMostrarGanador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 500, -1));

        etiquetaFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesTresEnRaya/nyancat1.gif"))); // NOI18N
        panelVentanaGanador.add(etiquetaFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVentanaGanador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVentanaGanador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the look and feel */
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.fast.FastLookAndFeel");
        } catch (ClassNotFoundException ex) {
            //Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            //Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            //Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            //Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //</editor-fold>
        String usuarioTurnoGanador = "user";
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaGanador dialog = new VentanaGanador(new javax.swing.JFrame(), true, usuarioTurnoGanador);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiquetaFondo;
    private javax.swing.JLabel etiquetaMostrarGanador;
    private javax.swing.JPanel panelVentanaGanador;
    // End of variables declaration//GEN-END:variables
}
