package Ventana;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author sebassvr
 */
public class VentanaCalculadora extends javax.swing.JFrame {
    private String cadenaNumeros = "";
    private double numero1, resultado;
    private String operacion = "nula";
    private boolean activado = true;
    private boolean punto = true;
    /**
     * Creates new form VentanaCalculadora
     */
    public VentanaCalculadora() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Calculadora");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panelBotonesCalculadora = new javax.swing.JPanel();
        botonC = new javax.swing.JButton();
        botonRaizCuadrada = new javax.swing.JButton();
        botonDividir = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonSiete = new javax.swing.JButton();
        botonOcho = new javax.swing.JButton();
        botonNueve = new javax.swing.JButton();
        botonMultiplicar = new javax.swing.JButton();
        botonCuatro = new javax.swing.JButton();
        botonCinco = new javax.swing.JButton();
        botonSeis = new javax.swing.JButton();
        botonRestar = new javax.swing.JButton();
        botonUno = new javax.swing.JButton();
        botonDos = new javax.swing.JButton();
        botonTres = new javax.swing.JButton();
        botonSumar = new javax.swing.JButton();
        botonMasMenos = new javax.swing.JButton();
        botonCero = new javax.swing.JButton();
        botonPunto = new javax.swing.JButton();
        botonIgual = new javax.swing.JButton();
        panelPantallaCalculadora = new javax.swing.JPanel();
        etiquetaMuestra = new javax.swing.JLabel();
        etiquetaNumeros = new javax.swing.JLabel();
        menuCalculadora = new javax.swing.JMenuBar();
        usos = new javax.swing.JMenu();
        calculadoraEstandar = new javax.swing.JMenuItem();
        conversordeDivisas = new javax.swing.JMenuItem();
        separador = new javax.swing.JPopupMenu.Separator();
        salir = new javax.swing.JMenuItem();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBotonesCalculadora.setLayout(new java.awt.GridLayout(5, 4, 1, 1));

        botonC.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 20)); // NOI18N
        botonC.setText("C");
        botonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCActionPerformed(evt);
            }
        });
        panelBotonesCalculadora.add(botonC);

        botonRaizCuadrada.setFont(new java.awt.Font("Gill Sans Ultra Bold", 3, 20)); // NOI18N
        botonRaizCuadrada.setText("√");
        botonRaizCuadrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRaizCuadradaActionPerformed(evt);
            }
        });
        panelBotonesCalculadora.add(botonRaizCuadrada);

        botonDividir.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 20)); // NOI18N
        botonDividir.setText("÷");
        botonDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDividirActionPerformed(evt);
            }
        });
        panelBotonesCalculadora.add(botonDividir);

        botonBorrar.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 20)); // NOI18N
        botonBorrar.setText("«");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });
        panelBotonesCalculadora.add(botonBorrar);

        botonSiete.setBackground(new java.awt.Color(205, 205, 205));
        botonSiete.setFont(new java.awt.Font("Lucida Console", 0, 20)); // NOI18N
        botonSiete.setText("7");
        botonSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSieteActionPerformed(evt);
            }
        });
        panelBotonesCalculadora.add(botonSiete);

        botonOcho.setBackground(new java.awt.Color(205, 205, 205));
        botonOcho.setFont(new java.awt.Font("Lucida Console", 0, 20)); // NOI18N
        botonOcho.setText("8");
        botonOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOchoActionPerformed(evt);
            }
        });
        panelBotonesCalculadora.add(botonOcho);

        botonNueve.setBackground(new java.awt.Color(205, 205, 205));
        botonNueve.setFont(new java.awt.Font("Lucida Console", 0, 20)); // NOI18N
        botonNueve.setText("9");
        botonNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNueveActionPerformed(evt);
            }
        });
        panelBotonesCalculadora.add(botonNueve);

        botonMultiplicar.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 20)); // NOI18N
        botonMultiplicar.setText("x");
        botonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMultiplicarActionPerformed(evt);
            }
        });
        panelBotonesCalculadora.add(botonMultiplicar);

        botonCuatro.setBackground(new java.awt.Color(205, 205, 205));
        botonCuatro.setFont(new java.awt.Font("Lucida Console", 0, 20)); // NOI18N
        botonCuatro.setText("4");
        botonCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCuatroActionPerformed(evt);
            }
        });
        panelBotonesCalculadora.add(botonCuatro);

        botonCinco.setBackground(new java.awt.Color(205, 205, 205));
        botonCinco.setFont(new java.awt.Font("Lucida Console", 0, 20)); // NOI18N
        botonCinco.setText("5");
        botonCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCincoActionPerformed(evt);
            }
        });
        panelBotonesCalculadora.add(botonCinco);

        botonSeis.setBackground(new java.awt.Color(205, 205, 205));
        botonSeis.setFont(new java.awt.Font("Lucida Console", 0, 20)); // NOI18N
        botonSeis.setText("6");
        botonSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeisActionPerformed(evt);
            }
        });
        panelBotonesCalculadora.add(botonSeis);

        botonRestar.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 20)); // NOI18N
        botonRestar.setText("-");
        botonRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestarActionPerformed(evt);
            }
        });
        panelBotonesCalculadora.add(botonRestar);

        botonUno.setBackground(new java.awt.Color(205, 205, 205));
        botonUno.setFont(new java.awt.Font("Lucida Console", 0, 20)); // NOI18N
        botonUno.setText("1");
        botonUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUnoActionPerformed(evt);
            }
        });
        panelBotonesCalculadora.add(botonUno);

        botonDos.setBackground(new java.awt.Color(205, 205, 205));
        botonDos.setFont(new java.awt.Font("Lucida Console", 0, 20)); // NOI18N
        botonDos.setText("2");
        botonDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDosActionPerformed(evt);
            }
        });
        panelBotonesCalculadora.add(botonDos);

        botonTres.setBackground(new java.awt.Color(205, 205, 205));
        botonTres.setFont(new java.awt.Font("Lucida Console", 0, 20)); // NOI18N
        botonTres.setText("3");
        botonTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTresActionPerformed(evt);
            }
        });
        panelBotonesCalculadora.add(botonTres);

        botonSumar.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 20)); // NOI18N
        botonSumar.setText("+");
        botonSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSumarActionPerformed(evt);
            }
        });
        panelBotonesCalculadora.add(botonSumar);

        botonMasMenos.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 20)); // NOI18N
        botonMasMenos.setText("±");
        botonMasMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMasMenosActionPerformed(evt);
            }
        });
        panelBotonesCalculadora.add(botonMasMenos);

        botonCero.setBackground(new java.awt.Color(205, 205, 205));
        botonCero.setFont(new java.awt.Font("Lucida Console", 0, 20)); // NOI18N
        botonCero.setText("0");
        botonCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCeroActionPerformed(evt);
            }
        });
        panelBotonesCalculadora.add(botonCero);

        botonPunto.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 20)); // NOI18N
        botonPunto.setText(".");
        botonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPuntoActionPerformed(evt);
            }
        });
        panelBotonesCalculadora.add(botonPunto);

        botonIgual.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 20)); // NOI18N
        botonIgual.setText("=");
        botonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIgualActionPerformed(evt);
            }
        });
        panelBotonesCalculadora.add(botonIgual);

        panelPantallaCalculadora.setLayout(new java.awt.GridLayout(2, 0));

        etiquetaMuestra.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        etiquetaMuestra.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        panelPantallaCalculadora.add(etiquetaMuestra);

        etiquetaNumeros.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 26)); // NOI18N
        etiquetaNumeros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaNumeros.setText("0");
        etiquetaNumeros.setAlignmentX(0.5F);
        etiquetaNumeros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelPantallaCalculadora.add(etiquetaNumeros);

        usos.setText("Usos");
        usos.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N

        calculadoraEstandar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        calculadoraEstandar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyectoCalculadora/iconCalculadora.png"))); // NOI18N
        calculadoraEstandar.setText("Calculadora Estándar");
        usos.add(calculadoraEstandar);

        conversordeDivisas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        conversordeDivisas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyectoCalculadora/iconConversordeDivisas.png"))); // NOI18N
        conversordeDivisas.setText("Conversor de Divisas");
        conversordeDivisas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conversordeDivisasActionPerformed(evt);
            }
        });
        usos.add(conversordeDivisas);
        usos.add(separador);

        salir.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyectoCalculadora/iconSalir.png"))); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        usos.add(salir);

        menuCalculadora.add(usos);

        setJMenuBar(menuCalculadora);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBotonesCalculadora, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPantallaCalculadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelPantallaCalculadora, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotonesCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void botonCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCeroActionPerformed
        if (cadenaNumeros != "") {
            if (etiquetaNumeros.getText() == "0") {
                cadenaNumeros = "0";
            }
            else{
                cadenaNumeros += "0";
            }
            etiquetaNumeros.setText(cadenaNumeros);
            activado = true;
        }
    }//GEN-LAST:event_botonCeroActionPerformed
    private void botonUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUnoActionPerformed
        if (etiquetaNumeros.getText() == "0") {
            cadenaNumeros = "1";
        }
        else{
            cadenaNumeros += "1";
        }
        etiquetaNumeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_botonUnoActionPerformed
    private void botonDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDosActionPerformed
        if (etiquetaNumeros.getText() == "0") {
            cadenaNumeros = "2";
        }
        else{
            cadenaNumeros += "2";
        }
        etiquetaNumeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_botonDosActionPerformed
    private void botonTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTresActionPerformed
        if (etiquetaNumeros.getText() == "0") {
            cadenaNumeros = "3";
        }
        else{
            cadenaNumeros += "3";
        }
        etiquetaNumeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_botonTresActionPerformed
    private void botonCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCuatroActionPerformed
        if (etiquetaNumeros.getText() == "0") {
            cadenaNumeros = "4";
        }
        else{
            cadenaNumeros += "4";
        }
        etiquetaNumeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_botonCuatroActionPerformed
    private void botonCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCincoActionPerformed
        if (etiquetaNumeros.getText() == "0") {
            cadenaNumeros = "5";
        }
        else{
            cadenaNumeros += "5";
        }
        etiquetaNumeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_botonCincoActionPerformed
    private void botonSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeisActionPerformed
        if (etiquetaNumeros.getText() == "0") {
            cadenaNumeros = "6";
        }
        else{
            cadenaNumeros += "6";
        }
        etiquetaNumeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_botonSeisActionPerformed
    private void botonSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSieteActionPerformed
        if (etiquetaNumeros.getText() == "0") {
            cadenaNumeros = "7";
        }
        else{
            cadenaNumeros += "7";
        }
        etiquetaNumeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_botonSieteActionPerformed
    private void botonOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOchoActionPerformed
        if (etiquetaNumeros.getText() == "0") {
            cadenaNumeros = "8";
        }
        else{
            cadenaNumeros += "8";
        }
        etiquetaNumeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_botonOchoActionPerformed
    private void botonNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNueveActionPerformed
        if (etiquetaNumeros.getText() == "0") {
            cadenaNumeros = "9";
        }
        else{
            cadenaNumeros += "9";
        }
        etiquetaNumeros.setText(cadenaNumeros);
        activado = true;
    }//GEN-LAST:event_botonNueveActionPerformed

    private void botonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPuntoActionPerformed
        if (punto == true) {
            if (cadenaNumeros == "") {
                cadenaNumeros = "0.";
            }
            else{
                cadenaNumeros += ".";
            }
            etiquetaNumeros.setText(cadenaNumeros);
            punto = false;
        }
    }//GEN-LAST:event_botonPuntoActionPerformed

    private void botonMasMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMasMenosActionPerformed
        if(cadenaNumeros != ""){
            if (cadenaNumeros.charAt(0) != '-') {
                cadenaNumeros = "-"+cadenaNumeros;
            }
            else {
                cadenaNumeros = cadenaNumeros.substring(1,cadenaNumeros.length());
            }
            etiquetaNumeros.setText(cadenaNumeros);
        }
        
    }//GEN-LAST:event_botonMasMenosActionPerformed

    private void botonSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSumarActionPerformed
        if (activado == true) {
            numero1 = Double.parseDouble(cadenaNumeros);
            etiquetaMuestra.setText(cadenaNumeros+" + ");
            cadenaNumeros = "";
            operacion = "sumar";
            
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_botonSumarActionPerformed

    private void botonRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestarActionPerformed
        if (activado == true) {
            numero1 = Double.parseDouble(cadenaNumeros);
            etiquetaMuestra.setText(cadenaNumeros+" - ");
            cadenaNumeros = "";
            operacion = "restar";
            
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_botonRestarActionPerformed

    private void botonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMultiplicarActionPerformed
        if (activado == true) {
            numero1 = Double.parseDouble(cadenaNumeros);
            etiquetaMuestra.setText(cadenaNumeros+" x ");
            cadenaNumeros = "";
            operacion = "multiplicar";
            
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_botonMultiplicarActionPerformed

    private void botonDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDividirActionPerformed
        if (activado == true) {
            numero1 = Double.parseDouble(cadenaNumeros);
            etiquetaMuestra.setText(cadenaNumeros+" / ");
            cadenaNumeros = "";
            operacion = "dividir";
            
            activado = false;
            punto = true;
        }
    }//GEN-LAST:event_botonDividirActionPerformed

    private void botonRaizCuadradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRaizCuadradaActionPerformed
        numero1 = Double.parseDouble(cadenaNumeros);
        etiquetaMuestra.setText("sqrt("+cadenaNumeros+")");
        resultado = Math.sqrt(numero1);
        etiquetaNumeros.setText(String.format("%.2f", resultado));
        cadenaNumeros = String.valueOf(resultado);
        punto = true;
    }//GEN-LAST:event_botonRaizCuadradaActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        int tamaño = cadenaNumeros.length();
        if (tamaño > 0) {
            if (tamaño ==1) {
                cadenaNumeros = "0";
            }
            else{
                cadenaNumeros = cadenaNumeros.substring(0, cadenaNumeros.length()-1);
                etiquetaNumeros.setText(cadenaNumeros);
            }
        }
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCActionPerformed
        etiquetaMuestra.setText("");
        etiquetaNumeros.setText("0");
        cadenaNumeros = "";
        operacion = "nulo";
        activado = true;
        punto = true;
    }//GEN-LAST:event_botonCActionPerformed

    private void botonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIgualActionPerformed
        double numero2;
        
        if (operacion.equals("nula")) {
            etiquetaNumeros.setText(cadenaNumeros);
        }
        else if (operacion.equals("sumar")) {
            numero2 = Double.parseDouble(cadenaNumeros);
            resultado = numero1 + numero2;
            etiquetaNumeros.setText(String.format("%.2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "nula";
        }
        else if (operacion.equals("restar")) {
            numero2 = Double.parseDouble(cadenaNumeros);
            resultado = numero1 - numero2;
            etiquetaNumeros.setText(String.format("%.2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "nula";
        }
        else if (operacion.equals("multiplicar")) {
            numero2 = Double.parseDouble(cadenaNumeros);
            resultado = numero1 * numero2;
            etiquetaNumeros.setText(String.format("%.2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "nula";
        }
        else if (operacion.equals("dividir")) {
            numero2 = Double.parseDouble(cadenaNumeros);
            resultado = numero1 / numero2;
            etiquetaNumeros.setText(String.format("%.2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "nula";
        }
        // 
        etiquetaMuestra.setText("");
        activado = true;
        
    }//GEN-LAST:event_botonIgualActionPerformed

    private void conversordeDivisasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conversordeDivisasActionPerformed
        VentanaDivisas conversor = new VentanaDivisas();
        conversor.setVisible(true);
        dispose();
    }//GEN-LAST:event_conversordeDivisasActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Establedemos el diseño. (LookAndFeel)
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.texture.TextureLookAndFeel");
        } catch (ClassNotFoundException ex) {
            //Logger.getLogger(VentanaDivisas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            //Logger.getLogger(VentanaDivisas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            //Logger.getLogger(VentanaDivisas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            //Logger.getLogger(VentanaDivisas.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonC;
    private javax.swing.JButton botonCero;
    private javax.swing.JButton botonCinco;
    private javax.swing.JButton botonCuatro;
    private javax.swing.JButton botonDividir;
    private javax.swing.JButton botonDos;
    private javax.swing.JButton botonIgual;
    private javax.swing.JButton botonMasMenos;
    private javax.swing.JButton botonMultiplicar;
    private javax.swing.JButton botonNueve;
    private javax.swing.JButton botonOcho;
    private javax.swing.JButton botonPunto;
    private javax.swing.JButton botonRaizCuadrada;
    private javax.swing.JButton botonRestar;
    private javax.swing.JButton botonSeis;
    private javax.swing.JButton botonSiete;
    private javax.swing.JButton botonSumar;
    private javax.swing.JButton botonTres;
    private javax.swing.JButton botonUno;
    private javax.swing.JMenuItem calculadoraEstandar;
    private javax.swing.JMenuItem conversordeDivisas;
    private javax.swing.JLabel etiquetaMuestra;
    private javax.swing.JLabel etiquetaNumeros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenuBar menuCalculadora;
    private javax.swing.JPanel panelBotonesCalculadora;
    private javax.swing.JPanel panelPantallaCalculadora;
    private javax.swing.JMenuItem salir;
    private javax.swing.JPopupMenu.Separator separador;
    private javax.swing.JMenu usos;
    // End of variables declaration//GEN-END:variables
}
