
package CarteleraCine;

/**
 *
 * @author sebassvr
 */
public class VentanaCartelera extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCartelera
     */
    public VentanaCartelera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelCarteleraScroll = new javax.swing.JScrollPane();
        panelCartelera = new javax.swing.JPanel();
        imagenLaRedSocial = new javax.swing.JLabel();
        titleLaRedSocial = new javax.swing.JLabel();
        genreLaRedSocial = new javax.swing.JLabel();
        imagenJobs = new javax.swing.JLabel();
        titleJobs = new javax.swing.JLabel();
        genreJobs = new javax.swing.JLabel();
        imagenElCodigoEnigma = new javax.swing.JLabel();
        titleElCodigoEnigma = new javax.swing.JLabel();
        genreElCodigoEnigma = new javax.swing.JLabel();
        imagenAprendicesFueradeLinea = new javax.swing.JLabel();
        titleAprendicesFueradeLinea = new javax.swing.JLabel();
        genreAprendicesFueradeLinea = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(480, 630));

        panelCartelera.setLayout(new java.awt.GridBagLayout());

        imagenLaRedSocial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesCartelera/LaRedSocial.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(13, 20, 13, 20);
        panelCartelera.add(imagenLaRedSocial, gridBagConstraints);

        titleLaRedSocial.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        titleLaRedSocial.setText("Title: La Red Social");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 20);
        panelCartelera.add(titleLaRedSocial, gridBagConstraints);

        genreLaRedSocial.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        genreLaRedSocial.setText("Genre: Drama");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelCartelera.add(genreLaRedSocial, gridBagConstraints);

        imagenJobs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesCartelera/Jobs.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.insets = new java.awt.Insets(13, 20, 13, 20);
        panelCartelera.add(imagenJobs, gridBagConstraints);

        titleJobs.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        titleJobs.setText("Title: Jobs");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 20);
        panelCartelera.add(titleJobs, gridBagConstraints);

        genreJobs.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        genreJobs.setText("Genre: Biographical film and drama");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelCartelera.add(genreJobs, gridBagConstraints);

        imagenElCodigoEnigma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesCartelera/ElCodigoEnigma.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.insets = new java.awt.Insets(13, 20, 13, 20);
        panelCartelera.add(imagenElCodigoEnigma, gridBagConstraints);

        titleElCodigoEnigma.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        titleElCodigoEnigma.setText("Title: El Código Enigma");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 20);
        panelCartelera.add(titleElCodigoEnigma, gridBagConstraints);

        genreElCodigoEnigma.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        genreElCodigoEnigma.setText("Genre: Drama");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelCartelera.add(genreElCodigoEnigma, gridBagConstraints);

        imagenAprendicesFueradeLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesCartelera/AprendicesFueradeLinea.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.insets = new java.awt.Insets(13, 20, 13, 20);
        panelCartelera.add(imagenAprendicesFueradeLinea, gridBagConstraints);

        titleAprendicesFueradeLinea.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        titleAprendicesFueradeLinea.setText("Title: Aprendices Fuera de Linea");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 20);
        panelCartelera.add(titleAprendicesFueradeLinea, gridBagConstraints);

        genreAprendicesFueradeLinea.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        genreAprendicesFueradeLinea.setText("Genre: Drama - Comedy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelCartelera.add(genreAprendicesFueradeLinea, gridBagConstraints);

        panelCarteleraScroll.setViewportView(panelCartelera);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCarteleraScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCarteleraScroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel genreAprendicesFueradeLinea;
    private javax.swing.JLabel genreElCodigoEnigma;
    private javax.swing.JLabel genreJobs;
    private javax.swing.JLabel genreLaRedSocial;
    private javax.swing.JLabel imagenAprendicesFueradeLinea;
    private javax.swing.JLabel imagenElCodigoEnigma;
    private javax.swing.JLabel imagenJobs;
    private javax.swing.JLabel imagenLaRedSocial;
    private javax.swing.JPanel panelCartelera;
    private javax.swing.JScrollPane panelCarteleraScroll;
    private javax.swing.JLabel titleAprendicesFueradeLinea;
    private javax.swing.JLabel titleElCodigoEnigma;
    private javax.swing.JLabel titleJobs;
    private javax.swing.JLabel titleLaRedSocial;
    // End of variables declaration//GEN-END:variables
}
